[env_conf]
# Maps used for training. Customize by keeping only desired map IDs, e.g. [1, 2] for maps 1 and 2.
# 训练使用的地图。可自定义选择期望用来训练的地图，如只期望使用1、2号地图训练数组内仅保留[1,2]即可。
map = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

map_random = true

#宝箱数量。可配置范围为0～10，每局将按照配置数量在道路上随机生成宝箱。
treasure_count = 10

#加速buff数量。可配置范围为0～2，每局将按照配置数量在道路上随机生成buff。
buff_count = 2

#加速buff刷新时间。buff被拾取后重新生成所需时间，单位为步数。可配置范围1～500。
buff_cooldown = 100

# 闪现技能冷却步数，闪现在施放后会进入冷却状态，冷却状态结束后重新激活。可配置范围为100~2000。
talent_cooldown = 100

#第二个怪物出现间隔。即开局多少步后，出现第二个怪物。可配置范围为-1,11～2000。-1即为在11～2000范围内随机生成对应配置。
monster_interval = 500

#怪物加速增益时间。即开局多少步后，怪物移动速度增加一格，可配置范围-1,1～2000。-1即为在1～2000范围内随机生成对应配置。
monster_speedup = 700

#最大步数，单局任务预测步数达到最大步数时，任务结束。可配置范围为1～2000。
max_step = 1000
